import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

# --- 1. Define Helper Functions ---

def sigmoid(v):
    """The Logistic CDF: 1 / (1 + exp(-v))"""
    return 1.0 / (1.0 + np.exp(-v))

def LogitExpectedLL(beta):
    """
    Calculates the Expected Log-Likelihood for the binary logit model.
    
    Parameters:
    beta (list or array): A 2-element vector [beta_1, beta_2] representing the intercept and slope.
    
    Returns:
    float: The expected log-likelihood value.
    """
    b1, b2 = beta
    
    # --- A. Setup True Parameters (from Problem 3) ---
    true_b1 = 1.0
    true_b2 = 2.0
    
    # --- B. Calculate True Probabilities (p0) ---
    # These are fixed "Truths" generated by beta_0 = (1, 2)
    p0_given_x0 = sigmoid(true_b1 + 0 * true_b2)  # p0(0)
    p0_given_x1 = sigmoid(true_b1 + 1 * true_b2)  # p0(1)
    
    # --- C. Calculate Model Probabilities (p) ---
    # These depend on the input 'beta' we are testing
    p_given_x0 = sigmoid(b1 + 0 * b2)  # p(0; beta)
    p_given_x1 = sigmoid(b1 + 1 * b2)  # p(1; beta)
    
    # --- D. Compute Cross-Entropy Terms ---
    # Avoid log(0) errors by adding a tiny epsilon if needed, though not strictly necessary for this range
    eps = 1e-15 
    
    # Expected LL given X=0
    term_x0 = (p0_given_x0 * np.log(p_given_x0 + eps) + 
               (1 - p0_given_x0) * np.log(1 - p_given_x0 + eps))
    
    # Expected LL given X=1
    term_x1 = (p0_given_x1 * np.log(p_given_x1 + eps) + 
               (1 - p0_given_x1) * np.log(1 - p_given_x1 + eps))
    
    # --- E. Weighted Average (Outer Expectation) ---
    # Weights are P(X=0)=0.25 and P(X=1)=0.75
    ell = 0.25 * term_x0 + 0.75 * term_x1
    
    return ell

# --- 2. Generate Data for Plotting ---

# Create a grid of beta values around the true values (1, 2)
beta1_range = np.linspace(-1, 3, 50)  # Range for Intercept
beta2_range = np.linspace(0, 4, 50)   # Range for Slope

B1, B2 = np.meshgrid(beta1_range, beta2_range)
Z = np.zeros_like(B1)

# Calculate Z (Expected LL) for every point on the grid
for i in range(B1.shape[0]):
    for j in range(B1.shape[1]):
        Z[i, j] = LogitExpectedLL([B1[i, j], B2[i, j]])

# --- 3. Create the 3D Plot ---

fig = plt.figure(figsize=(10, 7))
ax = fig.add_subplot(111, projection='3d')

# Plot the surface
surf = ax.plot_surface(B1, B2, Z, cmap='viridis', edgecolor='none', alpha=0.8)

# Mark the Theoretical Maximum
ax.scatter(1, 2, LogitExpectedLL([1, 2]), color='red', s=100, label='True Parameter (1, 2)')

# Labels and Title
ax.set_xlabel(r'$\beta_1$ (Intercept)')
ax.set_ylabel(r'$\beta_2$ (Slope)')
ax.set_zlabel('Expected Log-Likelihood')
ax.set_title('Expected Log-Likelihood Function Surface')
ax.legend()

# Show the plot
plt.show()

# --- 4. Print the Location of Maximum ---
print(f"The function is maximized at the true parameters:")
print(f"Beta_1 (Intercept): 1.0")
print(f"Beta_2 (Slope): 2.0")
print(f"Max Value: {LogitExpectedLL([1, 2]):.4f}")